Repository GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io, pull requests merged in 2021-11, with the labels that each got.

#161 about-pls
  _posts/2021-10-22-about-pls.md
  assets/images/post-about-pls/detail0.png
  assets/images/post-about-pls/detail1.png
  assets/images/post-about-pls/detail10.png
  assets/images/post-about-pls/detail11.png
  assets/images/post-about-pls/detail12.png
  assets/images/post-about-pls/detail13.png
  assets/images/post-about-pls/detail14.png
  assets/images/post-about-pls/detail15.png
  assets/images/post-about-pls/detail16.png
  assets/images/post-about-pls/detail17.png
  assets/images/post-about-pls/detail18.png
  assets/images/post-about-pls/detail2.png
  assets/images/post-about-pls/detail3.png
  assets/images/post-about-pls/detail4.png
  assets/images/post-about-pls/detail5.png
  assets/images/post-about-pls/detail6.png
  assets/images/post-about-pls/detail7.png
  assets/images/post-about-pls/detail8.png
  assets/images/post-about-pls/detail9.png
  assets/images/post-about-pls/intro.png
Labels: ✅ 리뷰 완료, 🛠 수정 완료

#160 [10월 FrontEnd Blog] React-Fiber-Architecture
  _posts/2021-10-22-react-fiber-architecture.md
  assets/images/post-react-fiber/cpu_1.png
  assets/images/post-react-fiber/cpu_2.png
  assets/images/post-react-fiber/fiber_instance.png
  assets/images/post-react-fiber/fiber_tree.png
  assets/images/post-react-fiber/fiber_tree2.png
Labels: ✅ 리뷰 완료, 🛠 수정 완료, 🙋‍♂️🙋‍♀️ 리뷰 요청

#162 [10월 backend blog] Nest.js Redux-saga with Socket.IO
  _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
  assets/images/post-Nestjs-Redux-Saga-SocketIO/image_1.png
  assets/images/post-Nestjs-Redux-Saga-SocketIO/image_2.png
  assets/images/post-Nestjs-Redux-Saga-SocketIO/thumbnail.png
Labels: ✅ 리뷰 완료, 🔨 수정 요청

#163 모바일팀 10월 포스팅입니다.
  _posts/2021-10-24-mobile_AAC.md
  assets/images/post-mobile-AAC/android_logo.png
  assets/images/post-mobile-AAC/room_architecture.png
  assets/images/post-mobile-AAC/viewmodel-lifecycle.png
Labels: 🔨 수정 요청

#170 2021-11-20-AlexNet.md
  _posts/2021-11-27-AlexNet.md
  assets/images/post-AlexNet/1.png
  assets/images/post-AlexNet/2.png
  assets/images/post-AlexNet/3.png
  assets/images/post-AlexNet/4.png
  assets/images/post-AlexNet/5.png
  assets/images/post-AlexNet/6.png
  assets/images/post-AlexNet/7.png
  assets/images/post-AlexNet/8.png
  assets/images/post-AlexNet/9.png
Labels: 🔨 수정 요청

#172 11월 FE팀 블로그포스팅
  _posts/2021-11-24-WASM.md
  assets/images/post-WASM/1200px-WebAssembly_Logo.svg.png
  assets/images/post-WASM/WasmAndJS.PNG
Labels: ✅ 리뷰 완료, 🔨 수정 요청, 🙋‍♂️🙋‍♀️ 리뷰 요청
