Repository GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io, pull requests merged in 2022-06, with the labels that each got.

#214 FE팀 4월 블로그 포스팅입니다.
  _posts/2022-05-15-Tailwind-CSS.md
  assets/images/post-Tailwind-CSS/Tailwind-icon.png
  assets/images/post-Tailwind-CSS/chitchat.png
  assets/images/post-Tailwind-CSS/css_frameworks_satisfaction_ranking.png
  assets/images/post-Tailwind-CSS/css_frameworks_usage_ranking.png
  assets/images/post-Tailwind-CSS/tailwind-site.svg
Labels: ✅ 리뷰 완료

#222 Data/ML 4월 포스팅입니다.
  _posts/2022-05-22-About-Coordinate-System.md
  assets/images/post-About-Coordinate-System/DBupload.png
  assets/images/post-About-Coordinate-System/area.png
  assets/images/post-About-Coordinate-System/postgis.png
  assets/images/post-About-Coordinate-System/seoul.png
  assets/images/post-About-Coordinate-System/thumbnail.png
  assets/images/post-About-Coordinate-System/구경계데이터_목록.png
  assets/images/post-About-Coordinate-System/서울시_구경계데이터_정보.png
Labels: ✅ 리뷰 완료

#216 FE 5월 블로그 포스팅입니다
  _posts/2022-05-22-about-CI-and-CD.md
  assets/images/post-about-ci-and-cd/ci-cd-flow.png
  assets/images/post-about-ci-and-cd/ci-cd-pipeline.jpg
Labels: ✅ 리뷰 완료

#221 5월 프론트 글 포스팅입니다
  _posts/2022-05-29-Login-by-JWT-HTTPS-COOKIE.md
  assets/images/post-Login-by-JWT-HTTPS-COOKIE/jwt1.png
  assets/images/post-Login-by-JWT-HTTPS-COOKIE/jwt2.png
  assets/images/post-Login-by-JWT-HTTPS-COOKIE/jwt3.png
  assets/images/post-Login-by-JWT-HTTPS-COOKIE/oauth.png
Labels: ✅ 리뷰 완료

#220 5월 프론트 글 후다닥
  _posts/2022-05-26-react-life-cycle.md
  assets/images/post-life-cycle/lifecycle_1.png
  assets/images/post-life-cycle/lifecycle_2.png
  assets/images/post-life-cycle/lifecycle_3.png
Labels: 🛠 수정 완료, 🙋‍♂️🙋‍♀️ 리뷰 요청

#217 ML 5월 블로그 포스팅입니다
  _posts/2022-05-22-bagging-randomforest-boosting.md
  assets/images/post-bagging-randomforest-boosting/bagging_graph.jpg
  assets/images/post-bagging-randomforest-boosting/boosting_algorithm.png
  assets/images/post-bagging-randomforest-boosting/boosting_graph.jpg
  assets/images/post-bagging-randomforest-boosting/cover.jpg
Labels: 🔨 수정 요청, 🙋‍♂️🙋‍♀️ 리뷰 요청

#218 5월 백엔드 블로그
  _posts/2022-05-24-foreign-key.md
  assets/images/post-foreign-key/1.png
  assets/images/post-foreign-key/2.png
Labels: ✅ 리뷰 완료
